import {create} from 'zustand';
import {locations} from '../data/locations';
import type {ActiveCurse, Category, Clue, CurseType, GameSnapshot, GameStore, LatLng, QuestionCard} from '../game/types';
import {closerCity,eastWest,haversineKm,insideRadar,northSouth,thermometerTrend} from '../game/geo/calculations';
import {isInsidePlayableRegion} from '../game/geo/possible-area';
import {calculateScore} from '../game/scoring/score';
import {seededRandom} from '../game/seed';
import {createQuestionCatalog} from '../game/questions/deck';
import {chooseCurseOptions,questionCategories,thresholds} from '../game/curses/select';
import {canAffordActionPoints,crossedThreatThresholds,deductActionPoints,jammedRadarResult,movementCost} from '../game/rules';

const newState=(seed:string):GameSnapshot=>{const random=seededRandom(seed),hidden=locations[Math.floor(random()*locations.length)]!,starts=locations.filter(place=>place.id!==hidden.id),start=starts[Math.floor(random()*starts.length)]!,catalog=createQuestionCatalog();return{seed,actionPoints:20,threat:0,questionsAsked:0,deck:[],hand:catalog,discardPile:[],clues:[],curses:[],curseHistory:[],pendingCurseChoices:[],pendingBurnCard:false,delayedClue:null,guess:null,hidden,searcher:{lat:start.lat,lng:start.lng},searcherName:start.name,previousSearcher:null,thermometerAvailable:false,movementTarget:null,moves:0};};
const cardCost=(card:QuestionCard)=>card.cost;
const isRadar=(card:QuestionCard)=>card.category==='Radar';
const canAsk=(s:GameSnapshot,card:QuestionCard)=>!s.curses.some(c=>c.type==='forced-move'&&haversineKm(c.origin,s.searcher)<30)&&!(card.kind==='thermometer'&&!s.thermometerAvailable);
const radarClue=(id:string,hidden:LatLng,center:LatLng,radius:number,jammed:boolean):Clue=>{const distance=haversineKm(hidden,center);if(!jammed){const result=insideRadar(hidden,center,radius);return{id,type:'radar',center,radiusKm:radius,result:result?'YES':'NO',constraintRadiusKm:radius,jammed:false,label:`RADAR ${radius} KM — ${result?'YES':'NO'}`};}const reading=jammedRadarResult(distance,radius);return{id,type:'radar',center,radiusKm:radius,result:reading.result,constraintRadiusKm:reading.constraintRadiusKm,jammed:true,label:`RADAR ${radius} KM — ${reading.result==='YES'?'DEFINITELY INSIDE':reading.result==='NO'?'DEFINITELY OUTSIDE':'UNCERTAIN'}`};};
const addChoices=(s:GameSnapshot,from:number,to:number,extra:CurseType[][]=[]):CurseType[][]=>[...extra,...crossedThreatThresholds(from,to).map(threshold=>chooseCurseOptions(`${s.seed}:curse:${threshold}`,s.curseHistory))];

export const useGameStore=create<GameStore>((set,get)=>({status:'playing',...newState('2026-09-27'),interactionCardId:null,pendingPair:null,resultScore:null,resultDistance:null,
startGame:(seed=`${new Date().toISOString().slice(0,10)}-${Date.now()}`)=>set({status:'playing',...newState(seed),interactionCardId:null,pendingPair:null,resultScore:null,resultDistance:null}),
playQuestion:(id)=>{const s=get(),card=s.hand.find(c=>c.id===id);if(!card||s.status!=='playing'||!canAsk(s,card))return;const cost=cardCost(card);if(!canAffordActionPoints(s.actionPoints,cost))return;if(card.kind==='closer-to'){set({status:'question-interaction',interactionCardId:id,pendingPair:[]});return;}if(['north-south','east-west','radar-100','radar-50','radar-25'].includes(card.kind)){const point=s.searcher;let clue:Clue;if(card.kind==='north-south'){const dir=northSouth(s.hidden,point).toLowerCase() as 'north'|'south';clue={id:`clue-${s.questionsAsked}`,type:'latitude-half-plane',originLat:point.lat,originLng:point.lng,validDirection:dir,label:`${dir.toUpperCase()} OF YOU`};}else if(card.kind==='east-west'){const dir=eastWest(s.hidden,point).toLowerCase() as 'east'|'west';clue={id:`clue-${s.questionsAsked}`,type:'longitude-half-plane',originLng:point.lng,originLat:point.lat,validDirection:dir,label:`${dir.toUpperCase()} OF YOU`};}else{const radius=card.kind==='radar-100'?100:card.kind==='radar-50'?50:25;clue=radarClue(`clue-${s.questionsAsked}`,s.hidden,point,radius,s.curses.some(c=>c.type==='signal-jam'));}resolve(card,cost,clue);return;}if(['population','coast','province','region','thermometer'].includes(card.kind)){const id=`clue-${s.questionsAsked}`;let clue:Clue;if(card.kind==='thermometer'){if(!s.previousSearcher)return;const trend=thermometerTrend(s.hidden,s.previousSearcher,s.searcher);clue={id,type:'thermometer',previous:s.previousSearcher,current:s.searcher,trend,label:`THERMOMETER: ${trend}`};}else if(card.kind==='population')clue={id,type:'population',bucket:s.hidden.population,label:`POPULATION: ${s.hidden.population}`};else if(card.kind==='coast')clue={id,type:'coast',bucket:s.hidden.coast,label:`COAST: ${s.hidden.coast}`};else if(card.kind==='province'){const reference=locations.reduce((nearest,place)=>haversineKm(place,s.searcher)<haversineKm(nearest,s.searcher)?place:nearest,locations[0]!);const sameProvince=s.hidden.province===reference.province;clue={id,type:'province-comparison',sameProvince,referenceProvince:reference.province,label:sameProvince?'SAME PROVINCE':'DIFFERENT PROVINCE'};}else clue={id,type:'region',region:s.hidden.region,label:`REGION: ${s.hidden.region.toUpperCase()}`};resolve(card,cost,clue);return;}set({status:'question-interaction',interactionCardId:id,pendingPair:null});},
beginMove:()=>{if(get().status==='playing')set({status:'moving',movementTarget:null});},setMovementTarget:(point)=>{if(get().status==='moving'&&isInsidePlayableRegion(point))set({movementTarget:point});},commitMove:()=>{const s=get();if(s.status!=='moving'||!s.movementTarget)return;const cost=movementCost(haversineKm(s.searcher,s.movementTarget));if(!canAffordActionPoints(s.actionPoints,cost))return;const newCurses=s.curses.filter(c=>c.type!=='forced-move'||haversineKm(c.origin,s.movementTarget!)<30);set({status:'playing',previousSearcher:s.searcher,thermometerAvailable:true,searcher:s.movementTarget,searcherName:'FIELD POSITION',movementTarget:null,actionPoints:deductActionPoints(s.actionPoints,cost),moves:s.moves+1,curses:newCurses,clues:s.delayedClue?[...s.clues,s.delayedClue]:s.clues,delayedClue:null});},
resolvePoint:(point)=>{const s=get(),card=s.hand.find(c=>c.id===s.interactionCardId);if(!card||!canAsk(s,card))return;let clue:Clue;if(card.kind==='north-south'){const dir=northSouth(s.hidden,point).toLowerCase() as 'north'|'south';clue={id:`clue-${s.questionsAsked}`,type:'latitude-half-plane',originLat:point.lat,originLng:point.lng,validDirection:dir,label:`${dir.toUpperCase()} OF SELECTED POINT`};}else if(card.kind==='east-west'){const dir=eastWest(s.hidden,point).toLowerCase() as 'east'|'west';clue={id:`clue-${s.questionsAsked}`,type:'longitude-half-plane',originLng:point.lng,originLat:point.lat,validDirection:dir,label:`${dir.toUpperCase()} OF SELECTED POINT`};}else{const radius=card.kind==='radar-100'?100:card.kind==='radar-50'?50:25;clue=radarClue(`clue-${s.questionsAsked}`,s.hidden,point,radius,s.curses.some(c=>c.type==='signal-jam'));}resolve(card,cardCost(card),clue);},
resolvePair:(a,b)=>{const s=get(),card=s.hand.find(c=>c.id===s.interactionCardId);if(!card||!canAsk(s,card))return;const cityA=locations.find(x=>x.id===a),cityB=locations.find(x=>x.id===b);if(!cityA||!cityB||a===b)return;const winner=closerCity(s.hidden,cityA,cityB)==='A'?cityA.id:cityB.id;resolve(card,cardCost(card),{id:`clue-${s.questionsAsked}`,type:'closer-to',cityA:a,cityB:b,winner,label:`CLOSER TO ${winner===a?cityA.name:cityB.name} THAN ${winner===a?cityB.name:cityA.name}`});},
enterGuessMode:()=>{const s=get();if(['playing','question-interaction','moving'].includes(s.status))set({status:'guessing',guess:null,interactionCardId:null,pendingPair:null,movementTarget:null});},cancelInteraction:()=>{const s=get();set({status:'playing',interactionCardId:null,pendingPair:null,guess:null,movementTarget:null,clues:s.delayedClue?[...s.clues,s.delayedClue]:s.clues,delayedClue:null});},setGuess:(guess)=>{if(get().status==='guessing'&&isInsidePlayableRegion(guess))set({guess});},submitGuess:()=>{const s=get();if(s.status!=='guessing'||!s.guess)return;const distance=haversineKm(s.guess,s.hidden);set({status:'finished',resultDistance:distance,resultScore:calculateScore(distance,s.questionsAsked),clues:s.delayedClue?[...s.clues,s.delayedClue]:s.clues,delayedClue:null});},
chooseCurse:(type)=>{const s=get(),options=s.pendingCurseChoices[0];if(!options?.includes(type)||s.curseHistory.at(-1)===type)return;const id=`curse-${s.curseHistory.length}-${s.threat}`,random=seededRandom(`${s.seed}:${id}:${type}`);let effect:ActiveCurse|null=null;switch(type){case'signal-jam':effect={id,type,radarsRemaining:2};break;case'question-tax':effect={id,type,category:questionCategories[Math.floor(random()*questionCategories.length)]!};break;case'forced-move':effect={id,type,origin:s.searcher};break;case'information-blackout':effect={id,type};break;case'burn-card':break;}const pending=s.pendingCurseChoices.slice(1),history=[...s.curseHistory,type];set({curses:effect?[...s.curses,effect]:s.curses,curseHistory:history,pendingCurseChoices:pending,pendingBurnCard:type==='burn-card',status:type==='burn-card'?'burn-choice':pending.length?'curse-choice':'playing'});},
resolveBurnChoice:(cardId)=>{const s=get();if(s.status!=='burn-choice')return;let hand=s.hand,discard=s.discardPile,deck=s.deck,threat=s.threat;if(cardId){const card=hand.find(c=>c.id===cardId);if(!card)return;hand=hand.filter(c=>c.id!==cardId);discard=[...discard,card];}else threat+=2;const choices=cardId?s.pendingCurseChoices:addChoices(s,s.threat,threat,s.pendingCurseChoices);set({hand,discardPile:discard,deck,threat,pendingBurnCard:false,pendingCurseChoices:choices,status:choices.length?'curse-choice':'playing'});},
dismissCurse:()=>{},tickCurse:()=>{},resetGame:()=>get().startGame()}));

function resolve(card:QuestionCard,cost:number,originalClue:Clue){const s=useGameStore.getState();const hand=s.hand,discard=s.discardPile,deck=s.deck;const taxed=s.curses.find(c=>c.type==='question-tax'&&c.category===card.category);const threat=s.threat+1+(taxed?2:0);const choices=addChoices(s,s.threat,threat,s.pendingCurseChoices);const blackout=s.curses.some(c=>c.type==='information-blackout');const clue=blackout?{...originalClue,label:`DELAYED · ${originalClue.label}`} as Clue:originalClue;let curses=s.curses.filter(c=>c.id!==taxed?.id);if(isRadar(card)){let used=false;curses=curses.flatMap(c=>{if(c.type!=='signal-jam'||used)return[c];used=true;return c.radarsRemaining>1?[{...c,radarsRemaining:c.radarsRemaining-1}]:[];});}if(blackout)curses=curses.filter(c=>c.type!=='information-blackout');const pendingClues=blackout?[...(s.delayedClue?[s.delayedClue]:[])]:[...(s.delayedClue?[s.delayedClue]:[]),clue];const delayedClue=blackout?clue:null;const applied=pendingClues.length?pendingClues:s.clues;const newlyAdded=applied===s.clues?[]:pendingClues;const nextClues=applied===s.clues?s.clues:[...s.clues,...newlyAdded];useGameStore.setState({status:choices.length?'curse-choice':'playing',interactionCardId:null,pendingPair:null,actionPoints:deductActionPoints(s.actionPoints,cost),threat,questionsAsked:s.questionsAsked+1,hand,deck,discardPile:discard,clues:nextClues,delayedClue,curses,thermometerAvailable:originalClue.type==='thermometer'?false:s.thermometerAvailable,pendingCurseChoices:choices,curseHistory:s.curseHistory});}
