'use client';
import {useEffect,useRef,useState} from 'react';
import maplibregl,{type Map as MLMap} from 'maplibre-gl';
import {circle} from '@turf/turf';
import {useGameStore} from '../store/gameStore';
import {locations} from '../data/locations';
import type {Clue,LatLng,QuestionKind} from '../game/types';
import {combineExcludedArea} from '../game/geo/possible-area';
const styleUrl=process.env.NEXT_PUBLIC_MAP_STYLE_URL||'https://tiles.openfreemap.org/styles/liberty';
const nlCenter: [number,number]=[5.35,52.15];

export default function GameMap({previewKind}:{previewKind:QuestionKind|null}){const ref=useRef<HTMLDivElement>(null),mapRef=useRef<MLMap|null>(null),gameSeedRef=useRef<string|null>(null),[ready,setReady]=useState(false);const seed=useGameStore(s=>s.seed),clues=useGameStore(s=>s.clues),status=useGameStore(s=>s.status),guess=useGameStore(s=>s.guess),resolvePoint=useGameStore(s=>s.resolvePoint),setMovementTarget=useGameStore(s=>s.setMovementTarget),searcher=useGameStore(s=>s.searcher),searcherName=useGameStore(s=>s.searcherName),movementTarget=useGameStore(s=>s.movementTarget),interactionCardId=useGameStore(s=>s.interactionCardId),hidden=useGameStore(s=>s.hidden),resultDistance=useGameStore(s=>s.resultDistance);const card=useGameStore(s=>s.hand.find(c=>c.id===s.interactionCardId));
useEffect(()=>{if(!ref.current||mapRef.current)return;const map=new maplibregl.Map({container:ref.current,style:styleUrl,center:nlCenter,zoom:6.7,minZoom:5,maxZoom:13,dragRotate:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{map.addSource('possible-area',{type:'geojson',data:combineExcludedArea([]) as never});map.addLayer({id:'possible-area-fill',type:'fill',source:'possible-area',paint:{'fill-color':'#bf382d','fill-opacity':0.24}});map.addLayer({id:'possible-area-edge',type:'line',source:'possible-area',paint:{'line-color':'#bf382d','line-width':1.5,'line-opacity':0.78}});map.addSource('card-preview',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'card-preview-fill',type:'fill',source:'card-preview',paint:{'fill-color':'#bf382d','fill-opacity':0.08}});map.addLayer({id:'card-preview-line',type:'line',source:'card-preview',paint:{'line-color':'#bf382d','line-width':2,'line-dasharray':[2,2]}});map.addSource('searcher',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'searcher-marker',type:'circle',source:'searcher',paint:{'circle-radius':8,'circle-color':'#236f58','circle-stroke-color':'#fffdf7','circle-stroke-width':2.5}});map.addSource('thermometer-clues',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'thermometer-lines',type:'line',source:'thermometer-clues',paint:{'line-color':['match',['get','trend'],'HOTTER','#bf382d','#495b54'],'line-width':2.5,'line-dasharray':[1,1]}});map.addSource('move-route',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'move-route-line',type:'line',source:'move-route',paint:{'line-color':'#236f58','line-width':2,'line-dasharray':[2,2]}});map.addSource('markers',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'markers',type:'circle',source:'markers',paint:{'circle-radius':6,'circle-color':'#bd3429','circle-stroke-color':'#fffdf7','circle-stroke-width':2}});map.addSource('answer',{type:'geojson',data:{type:'FeatureCollection',features:[]} as never});map.addLayer({id:'answer-line',type:'line',source:'answer',filter:['==',['geometry-type'],'LineString'],paint:{'line-color':'#171715','line-width':2,'line-dasharray':[1,2]}});map.addLayer({id:'answer-dot',type:'circle',source:'answer',filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':6,'circle-color':'#171715','circle-stroke-color':'#fffdf7','circle-stroke-width':2}});setReady(true);});map.on('click',(e)=>{const p={lat:e.lngLat.lat,lng:e.lngLat.lng};const s=useGameStore.getState();if(s.status==='guessing')s.setGuess(p);else if(s.status==='moving')s.setMovementTarget(p);else if(s.status==='question-interaction'&&s.interactionCardId&&s.hand.find(c=>c.id===s.interactionCardId)?.kind!=='closer-to')s.resolvePoint(p);});mapRef.current=map;return()=>{map.remove();mapRef.current=null};},[]);
useEffect(()=>{if(!ready)return;const map=mapRef.current!;if(seed!==gameSeedRef.current){gameSeedRef.current=seed;map.easeTo({center:nlCenter,zoom:6.7,bearing:0,duration:500});(map.getSource('answer') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:[]} as never);}(map.getSource('searcher') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[searcher.lng,searcher.lat]}}]} as never);(map.getSource('thermometer-clues') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:clues.filter((clue):clue is Extract<Clue,{type:'thermometer'}>=>clue.type==='thermometer').map(clue=>({type:'Feature',properties:{trend:clue.trend},geometry:{type:'LineString',coordinates:[[clue.previous.lng,clue.previous.lat],[clue.current.lng,clue.current.lat]]}}))} as never);(map.getSource('move-route') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:movementTarget?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[searcher.lng,searcher.lat],[movementTarget.lng,movementTarget.lat]]}}]:[]} as never);const selected=clues.filter(c=>c.type==='radar'||c.type==='latitude-half-plane'||c.type==='longitude-half-plane').map((c)=>c.type==='radar'?{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[c.center.lng,c.center.lat]}}:c.type==='latitude-half-plane'?{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[c.originLng??searcher.lng,c.originLat]}}:c.type==='longitude-half-plane'?{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[c.originLng,c.originLat??searcher.lat]}}:{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[5.3,52]}});const markers=[...selected,...(guess?[{type:'Feature',properties:{guess:true},geometry:{type:'Point',coordinates:[guess.lng,guess.lat]}}]:[])];(map.getSource('markers') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:markers} as never);if(status==='finished'){const answer=useGameStore.getState().hidden,guessNow=useGameStore.getState().guess;if(guessNow){(map.getSource('answer') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[guessNow.lng,guessNow.lat],[answer.lng,answer.lat]]}},{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[answer.lng,answer.lat]}}]} as never);map.fitBounds([[Math.min(guessNow.lng,answer.lng)-.18,Math.min(guessNow.lat,answer.lat)-.18],[Math.max(guessNow.lng,answer.lng)+.18,Math.max(guessNow.lat,answer.lat)+.18]],{padding:60,duration:800,maxZoom:10});}}},[clues,guess,status,ready,searcher,movementTarget,seed]);
useEffect(()=>{if(!ready)return;const source=mapRef.current?.getSource('possible-area') as maplibregl.GeoJSONSource|undefined;source?.setData(combineExcludedArea(clues) as never);},[clues,ready]);
useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;const source=map.getSource('card-preview') as maplibregl.GeoJSONSource;if(!previewKind||!['north-south','east-west','radar-100','radar-50','radar-25'].includes(previewKind)){source.setData({type:'FeatureCollection',features:[]} as never);return;}let feature:GeoJSON.Feature;if(previewKind==='radar-100'||previewKind==='radar-50'||previewKind==='radar-25'){const radius=previewKind==='radar-100'?100:previewKind==='radar-50'?50:25;feature=circle([searcher.lng,searcher.lat],radius,{steps:64,units:'kilometers'});}else{feature={type:'Feature',properties:{},geometry:{type:'LineString',coordinates:previewKind==='north-south'?[[3.35,searcher.lat],[7.25,searcher.lat]]:[[searcher.lng,50.65],[searcher.lng,53.65]]}};}source.setData({type:'FeatureCollection',features:[feature]} as never);},[previewKind,ready,searcher]);
useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;map.getCanvas().style.cursor=status==='guessing'||status==='moving'?'crosshair':status==='question-interaction'?(card?.kind==='closer-to'?'default':'crosshair'):'grab';},[status,card,ready]);
return <div className="map-shell"><div ref={ref} className="map-canvas" aria-label="Map of the Netherlands. Click to place a question marker or final guess."/><div className="map-stamp">NETHERLANDS <span>52° N / 5° E</span></div><div className="searcher-stamp">SEARCHER <b>{searcherName.toUpperCase()}</b></div>{previewKind&&(['north-south','east-west','radar-100','radar-50','radar-25'].includes(previewKind))&&<div className="preview-stamp">CARD RANGE · SEARCHER POSITION</div>}{status==='moving'&&<div className="map-instruction">MOVE SEARCHER <span>{movementTarget?'DESTINATION SELECTED':'CLICK MAP TO CHOOSE DESTINATION'}</span></div>}{status==='guessing'&&<div className="map-instruction">PLACE YOUR FINAL GUESS <span>{guess?'POSITION SET':'CLICK MAP TO PLACE'}</span></div>}{status==='finished'&&<div className="map-stamp result-stamp">ANSWER — {hidden.name.toUpperCase()} · {resultDistance?.toFixed(1)} KM</div>}</div>;
}
