'use client';
import {useEffect,useState} from 'react';
import {AnimatePresence,LayoutGroup,motion,useReducedMotion} from 'framer-motion';
import GameMap from './GameMap';
import QuestionCard from './QuestionCard';
import ThreatMeter from './ThreatMeter';
import ClueHistory from './ClueHistory';
import InfoHint from './InfoHint';
import {useGameStore} from '../store/gameStore';
import {locations} from '../data/locations';
import {haversineKm} from '../game/geo/calculations';
import {movementCost} from '../game/rules';
import type {Clue,CurseType,QuestionKind} from '../game/types';

const curseCopy:Record<CurseType,{title:string;body:string}>={
  'signal-jam':{title:'SIGNAL JAM',body:'Your next two radar scans may return UNCERTAIN.'},
  'question-tax':{title:'QUESTION TAX',body:'Your next question in one category adds 2 Threat.'},
  'forced-move':{title:'FORCED MOVE',body:'Move at least 30 km before asking again.'},
  'information-blackout':{title:'INFORMATION BLACKOUT',body:'Your next answer waits until your next turn.'},
  'burn-card':{title:'BURN CARD',body:'Discard one card or accept 2 Threat.'}
};
const curseBody=(type:CurseType)=>type==='burn-card'?'Choose one card to burn, or take +2 Threat.':curseCopy[type].body;
export default function Game(){
  const ap=useGameStore(s=>s.actionPoints),threat=useGameStore(s=>s.threat),hand=useGameStore(s=>s.hand),status=useGameStore(s=>s.status),curses=useGameStore(s=>s.curses),curseHistory=useGameStore(s=>s.curseHistory),curseChoices=useGameStore(s=>s.pendingCurseChoices[0]),chooseCurse=useGameStore(s=>s.chooseCurse),resolveBurn=useGameStore(s=>s.resolveBurnChoice),delayedClue=useGameStore(s=>s.delayedClue),clues=useGameStore(s=>s.clues),guess=useGameStore(s=>s.guess),cancel=useGameStore(s=>s.cancelInteraction),submit=useGameStore(s=>s.submitGuess),enterGuess=useGameStore(s=>s.enterGuessMode),score=useGameStore(s=>s.resultScore),distance=useGameStore(s=>s.resultDistance),questions=useGameStore(s=>s.questionsAsked),reset=useGameStore(s=>s.resetGame),playQuestion=useGameStore(s=>s.playQuestion),searcher=useGameStore(s=>s.searcher),movementTarget=useGameStore(s=>s.movementTarget),beginMove=useGameStore(s=>s.beginMove),commitMove=useGameStore(s=>s.commitMove);
  const [pair,setPair]=useState<[string,string]>(['','']),[copied,setCopied]=useState(false),[threshold,setThreshold]=useState<number|null>(null),[reveal,setReveal]=useState<Clue|null>(null),[resultOpen,setResultOpen]=useState(true),[previewKind,setPreviewKind]=useState<QuestionKind|null>(null),[armedCardId,setArmedCardId]=useState<string|null>(null);
  const reduced=useReducedMotion(),card=useGameStore(s=>s.hand.find(c=>c.id===s.interactionCardId)),armedCard=hand.find(c=>c.id===armedCardId),moveCost=movementTarget?movementCost(haversineKm(searcher,movementTarget)):null,resolvePair=useGameStore(s=>s.resolvePair);
  const groups=(['Direction','Radar','Comparison','Profile'] as const).map(category=>({category,cards:hand.filter(c=>c.category===category)})).filter(group=>group.cards.length>0);
  useEffect(()=>{setPreviewKind(null);setArmedCardId(null);const latest=clues.at(-1);if(!latest)return;setReveal(latest);const t=setTimeout(()=>setReveal(null),2400);return()=>clearTimeout(t)},[clues]);
  useEffect(()=>{if(status==='finished')setResultOpen(true)},[status]);
  useEffect(()=>{if(threat===0||![3,5,7,9].includes(threat))return;setThreshold(threat);const t=setTimeout(()=>setThreshold(null),1700);return()=>clearTimeout(t)},[threat]);
  const share=async()=>{const message=`HIDDEN\n📍 ${distance?.toFixed(1)} km\n❓ ${questions} questions\n⚡ Threat ${threat}\n⭐ ${score?.toLocaleString('en-US')}`;try{await navigator.clipboard.writeText(message);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setCopied(false)}};
  const categoryFor=(type:CurseType)=>type==='question-tax'?' · PICKED CATEGORY': '';
  return <main className="app-frame"><header className="topbar"><a className="wordmark" href="#">HIDDEN<span>®</span></a><div className="round-tag"><i/> QUICK GAME <span>01 / NETHERLANDS</span></div><div className="top-meta"><span>FIELD UNIT&nbsp; 01</span><span>LOCAL SESSION</span></div></header>
    <div className="game-grid"><section className="map-column"><div className="map-topline"><span>THE NETHERLANDS</span><span>51° 30′ — 53° 33′ N</span></div><GameMap previewKind={armedCard?.kind??previewKind}/></section>
      <aside className="control-column"><div className="stats-row"><div className="ap-block"><div className="metric-label"><span>ACTION POINTS <InfoHint label="Action Points" text="Start with 20 AP. Asking questions and moving spend AP; guessing is free."/></span></div><div className="ap-number">{String(ap).padStart(2,'0')}<small> / 20</small></div><div className="ap-track"><i style={{width:`${ap/20*100}%`}}/></div></div><ThreatMeter threat={threat}/></div><div className="control-scroll">
        {curses.length>0&&<section className="active-curses"><div className="section-heading"><span>ACTIVE PRESSURE <InfoHint label="Active Pressure" text="Curses currently affecting this round. The note beside each one tells you what it changes."/></span><span>{curses.length}</span></div>{curses.map(c=><div key={c.id}><b>{curseCopy[c.type].title}{categoryFor(c.type)}</b><span>{c.type==='signal-jam'?`${c.radarsRemaining} RADAR READINGS LEFT`:c.type==='question-tax'?`NEXT ${c.category.toUpperCase()} +2 THREAT`:c.type==='forced-move'?'MOVE 30 KM BEFORE A QUESTION':c.type==='information-blackout'?'NEXT ANSWER HELD ONE TURN':''}</span></div>)}</section>}
        {delayedClue&&<div className="delayed-note">ANSWER HELD · MOVE OR TAKE ANOTHER TURN TO REVEAL</div>}
        <div className="hand-heading"><div><span className="eyebrow">FULL QUESTION CATALOG</span><h1>Choose a question<span>—</span></h1></div><span className="hand-count">{hand.length} AVAILABLE</span></div><p className="brief-copy">All question types are available from the start. AP limits how many you can ask.</p><div className="question-groups">{groups.map(group=><section className="question-group" key={group.category}><div className="question-group-heading"><span>{group.category.toUpperCase()}</span><span>{String(group.cards.length).padStart(2,'0')}</span></div><div className="hand-list">{group.cards.map((c,i)=><QuestionCard key={c.id} card={c} index={i} selected={armedCardId===c.id} onPreview={kind=>setPreviewKind(kind)} onChoose={setArmedCardId}/>)}</div></section>)}</div>
</div><ClueHistory/><div className="control-actions">        {armedCard&&status==='playing'&&<div className="armed-controls"><span>SELECTED · {armedCard.label} · {armedCard.cost} AP{armedCard.category==='Radar'&&curses.some(c=>c.type==='signal-jam')?' · SIGNAL JAM':''}</span><div><button onClick={()=>{playQuestion(armedCard.id);setArmedCardId(null);setPreviewKind(null)}}>ASK QUESTION <b>↗</b></button><button onClick={()=>{setArmedCardId(null);setPreviewKind(null)}}>CANCEL</button></div></div>}         {status==='question-interaction'&&card?.kind==='closer-to'&&<div className="pair-picker"><div className="pair-label">CHOOSE TWO CITIES</div><div className="pair-selects"><select value={pair[0]} onChange={e=>setPair([e.target.value,pair[1]])}><option value="">CITY A</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><span>VS</span><select value={pair[1]} onChange={e=>setPair([pair[0],e.target.value])}><option value="">CITY B</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="pair-actions"><button onClick={()=>pair[0]&&pair[1]&&resolvePair(pair[0],pair[1])} disabled={!pair[0]||!pair[1]||pair[0]===pair[1]}>ASK QUESTION</button><button onClick={()=>{cancel();setPair(['',''])}}>CANCEL</button></div></div>}         {status==='moving'&&<div className="move-controls"><p>{movementTarget?`Destination set · ${haversineKm(searcher,movementTarget).toFixed(0)} km · ${moveCost} AP`:'Choose a destination on the map. Every 50 km costs 1 AP.'}</p><div><button onClick={commitMove} disabled={!movementTarget||moveCost!==null&&moveCost>ap}>MOVE / {moveCost??'—'} AP</button><button onClick={cancel}>CANCEL</button></div></div>}         {status==='guessing'&&<div className="guess-controls"><p>Place a point anywhere in the Netherlands.</p><div><button onClick={submit} disabled={!guess}>LOCK IN</button><button onClick={cancel}>CANCEL</button></div></div>}<div className="decision-row"><span>{status==='moving'?'MOVE OR CANCEL':status==='question-interaction'?'TARGET REQUIRED':status==='guessing'?'FINAL POSITION':status==='curse-choice'?'CHOOSE YOUR CURSE':status==='burn-choice'?'BURN OR TAKE THREAT':'ONE ACTION PER TURN'}</span><div className="decision-actions"><button className="move-button" onClick={()=>{setArmedCardId(null);setPreviewKind(null);beginMove()}} disabled={status!=='playing'||ap<1}>MOVE <b>↗</b></button><button className="guess-button" onClick={()=>{setArmedCardId(null);setPreviewKind(null);status==='guessing'?submit():enterGuess()}} disabled={status==='finished'||status==='guessing'&&!guess}>{status==='guessing'?'LOCK IN GUESS':'GUESS'} <b>↗</b></button></div></div></div>
      </aside>
    </div>
    <footer className="app-footer"><span>HIDDEN / QUICK GAME</span><span>v 1.0.0</span></footer>
    <AnimatePresence>{reveal&&<motion.div className="clue-reveal" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}}><span>{reveal.type==='province-comparison'?'RELATIVE PROVINCE ANSWER':'EVIDENCE RECORDED'}</span><strong>{reveal.label}</strong></motion.div>}
      {threshold&&<motion.div className="threshold-flash" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span>THREAT LEVEL {threshold}</span></motion.div>}
      {curseChoices&&<motion.div className="curse-choice-screen" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="curse-choice-panel"><div className="curse-kicker">FALSE CHOICE · THREAT {threat}</div><h2>CHOOSE THE CONSEQUENCE</h2><p>Two outcomes. You decide what the hunt costs.</p><div className="curse-options">{curseChoices.filter(type=>type!==curseHistory.at(-1)).map(type=><button key={type} onClick={()=>chooseCurse(type)}><b>{curseCopy[type].title}</b><span>{curseBody(type)}</span><i>TAKE THIS CURSE ↗</i></button>)}</div></div></motion.div>}
      {status==='burn-choice'&&<motion.div className="curse-choice-screen" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="curse-choice-panel"><div className="curse-kicker">BURN CARD</div><h2>PAY A PRICE</h2><p>Discard a card from your hand, or let Threat rise by two.</p><div className="burn-options">{hand.map(c=><button key={c.id} onClick={()=>resolveBurn(c.id)}>BURN · {c.label}</button>)}<button className="burn-threat" onClick={()=>resolveBurn(null)}>TAKE +2 THREAT</button></div></div></motion.div>}
      {status==='finished'&&<LayoutGroup id="result-morph"><AnimatePresence mode="sync">{resultOpen?<motion.div key="result-open" className="result-screen" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.2}} role="dialog" aria-modal="true" aria-label="Game result"><motion.div layoutId="result-shape" className="result-panel" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{layout:{type:'spring',stiffness:260,damping:28},duration:reduced?0:.18}}><div className="result-top"><span>CASE CLOSED</span><span>QUICK GAME / 01</span><button className="result-close" aria-label="Close results" onClick={()=>setResultOpen(false)}>CLOSE ×</button></div><div className="result-kicker">THE LOCATION WAS</div><h2>{useGameStore.getState().hidden.name.toUpperCase()}</h2><div className="result-distance">{distance?.toFixed(1)} <small>KM AWAY</small></div><div className="result-facts"><span>{questions} QUESTIONS</span><span>{ap} AP REMAINING</span><span>THREAT {threat}</span></div><div className="score-label">FINAL SCORE</div><div className="result-score">{score?.toLocaleString('en-US')}</div><div className="result-actions"><button onClick={reset}>PLAY AGAIN <b>↗</b></button><button onClick={share}>{copied?'COPIED':'SHARE RESULT'} <b>⤴</b></button></div><p>Distance decides. Restraint counts.</p></motion.div></motion.div>:<motion.button layoutId="result-shape" key="result-closed" className="result-reopen" initial={{opacity:0,y:reduced?0:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduced?0:8}} transition={{duration:reduced?0:.2}} onClick={()=>setResultOpen(true)}>SHOW RESULT <b>↗</b></motion.button>}</AnimatePresence></LayoutGroup>}
    </AnimatePresence>
  </main>;
}
